" vim:foldmethod=marker
"

" Helps airline glyphs display in Windows
set encoding=utf-8

" setup tips {{{
"
" Before this .vimrc can be used:
"
" - Install Vundle:
"
"   git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
"
" Run PluginSearch! (with a bang) the first time.  This will ensure that the
" cache is built up.
"
" And to install the included plugins:
"
"   vim +PluginInstall +qa
"
" After editing the config, to uninstall unused plugins:
"
"   vim +PluginClean
"
" }}}

" vundle {{{
set nocompatible
filetype off

" set runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" all of your plugins must be added before the following line
call vundle#end()
filetype plugin indent on

" :PluginList
" - List configured plugins.
" :PluginInstall
" - Install plugins.  Append ! to update.
" :PluginUpdate
" - Update plugins.
" :PluginSearch foo
" - Searches for a plugin.  Append ! to refresh local cache.
" :PluginClean
" - Remove unused plugins.  Append ! for non-interactive deinstall.
"
" See :help vundle for details.

" }}}

" plugins {{{

" themes {{{
Plugin 'CruizeMissile/Revolution.vim'
Plugin 'jlesquembre/peaksea'
Plugin 'romainl/flattened'
Plugin 'jaimebuelta/jaime-vim-colorscheme'
" }}}

" vim-javascript - Javascript syntax and tweaks {{{
Plugin 'pangloss/vim-javascript'
" }}}

" vim-json - JSON syntax and tweaks {{{
Plugin 'elzr/vim-json'
" }}}

" syntastic - Linting integration {{{
Plugin 'scrooloose/syntastic'

" From the documentation...
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

" Customizations
let g:syntastic_javascript_checkers = ['eslint']
" }}}

" nerdtree - File tree {{{
Plugin 'scrooloose/nerdtree'
" }}}

" airline - Status bar {{{
Plugin 'bling/vim-airline'

" Use special symbols in the status bar.
let g:airline_powerline_fonts = 1

" Ensure that airline is visible at all times.
set laststatus=2

" List buffers along the top
let g:airline#extensions#tabline#enabled = 1

" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'
" }}}

" ctrlp - Fuzzy search {{{
Plugin 'kien/ctrlp.vim'
" }}}

" indentguides - Show vertical lines for indentation levels {{{
Plugin 'nathanaelkane/vim-indent-guides'
" }}}

" delimitMate - Handle automatically matching pairs of parens/brackets/etc {{{
Plugin 'Raimondi/delimitMate'
" }}}

" undotree - Visualize the undo tree {{{
Plugin 'mbbill/undotree'
" }}}

" fugitive - Git bindings and commands {{{
Plugin 'tpope/vim-fugitive'
" }}}

" autoclose-tag - Automatically close HTML tags {{{
Plugin 'amirh/HTML-AutoCloseTag'
" }}}

" }}}

" bindings  {{{
let mapleader=';'
map <C-e> :NERDTreeToggle<CR>
nmap <Leader>e :NERDTreeFind<CR>
nmap <Leader>u :UndotreeToggle<CR>
nmap <Leader>tn :tabnew<CR>
nmap <Leader>tc :tabclose<CR>
nmap <Leader>tC :tabonly<CR>
nmap <Leader>tt :tabnext<CR>
nmap <Leader>tT :tabprev<CR>
nmap <leader>bc :bp <BAR> bd #<CR>
nmap <leader>bb :bn<CR>
" }}}

" prefs {{{
set hidden
" }}}

" asthetics {{{
 
colorscheme jaime
let g:airline_theme='molokai'
" colorscheme flattened_dark
syntax on

" In gvim, use a font the includes the special powerline symbols.
set guifont=Meslo_LG_S_for_Powerline:h9:cANSI,Menlo\ for\ Powerline:h11

" Show normal mode commands
set showcmd

" Highlight all matches after a search
set hls

" Hide the toolbar in the GUI
set guioptions-=T

" }}}

" indentation {{{
set tabstop=8
set shiftwidth=4
set softtabstop=4
set noexpandtab
" }}}

" file specific settings {{{
augroup file_specific_settings
    autocmd!
    autocmd BufEnter .jshintrc setlocal filetype=json
    autocmd BufEnter .eslintrc setlocal filetype=json
augroup END
" }}}

" windows-specific-settings {{{
if has('windows')
    let $PATH = 'C:\Program Files (x86)\Git\bin;' . $PATH
    set shell=C:\Progra~2\Git\bin\bash.exe
endif
" }}}

" - chris
