" vim:foldmethod=marker
"

" Helps airline glyphs display in Windows
set encoding=utf8

" setup tips {{{
"
" Before this .vimrc can be used:
"
" - Install Vundle:
"
"   git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
"
" Run PluginSearch! (with a bang) the first time.  This will ensure that the
" cache is built up.
"
" And to install the included plugins:
"
"   vim +PluginInstall +qa
"
" After editing the config, to uninstall unused plugins:
"
"   vim +PluginClean
"
" }}}

" vundle {{{
set nocompatible
filetype off

" set runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" all of your plugins must be added before the following line
call vundle#end()
filetype plugin indent on

" :PluginList
" - List configured plugins.
" :PluginInstall
" - Install plugins.  Append ! to update.
" :PluginUpdate
" - Update plugins.
" :PluginSearch foo
" - Searches for a plugin.  Append ! to refresh local cache.
" :PluginClean
" - Remove unused plugins.  Append ! for non-interactive deinstall.
"
" See :help vundle for details.

" }}}

" plugins {{{

" themes {{{
Plugin 'dracula/vim'
" }}}

" vim-javascript - Javascript syntax and tweaks {{{
Plugin 'pangloss/vim-javascript'
" }}}

" vim-json - JSON syntax and tweaks {{{
Plugin 'elzr/vim-json'
" }}}

" syntastic - Linting integration {{{
Plugin 'scrooloose/syntastic'

" From the documentation...
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

" Customizations
let g:syntastic_javascript_checkers = ['eslint']
" }}}

" nerdtree - File tree {{{
Plugin 'scrooloose/nerdtree'
" }}}

" airline - Status bar {{{
Plugin 'bling/vim-airline'

" Use special symbols in the status bar.
let g:airline_powerline_fonts = 1

" Ensure that airline is visible at all times.
set laststatus=2

" List buffers along the top
let g:airline#extensions#tabline#enabled = 1

" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'

" Show index of buffers
let g:airline#extensions#tabline#buffer_nr_show = 1
" }}}

"airline-themes - Themes for Status bar {{{
Plugin 'vim-airline/vim-airline-themes'
"}}}

" ctrlp - Fuzzy search {{{
Plugin 'ctrlpvim/ctrlp.vim'
" }}}

" delimitMate - Handle automatically matching pairs of parens/brackets/etc {{{
Plugin 'Raimondi/delimitMate'
" }}}

" undotree - Visualize the undo tree {{{
Plugin 'mbbill/undotree'
" }}}

" fugitive - Git bindings and commands {{{
Plugin 'tpope/vim-fugitive'
" }}}

" emmet - Expand macros to HTML {{{
Plugin 'mattn/emmet-vim'
" }}}

" bufexplorer - A rich buffer list {{{
Plugin 'vim-scripts/bufexplorer.zip'
" }}}

" editorconfig - Interprets editor agnostic configuration files {{{
Plugin 'editorconfig/editorconfig-vim'
" }}}

" nerdtree-git-plugin - A plugin for viewing git status in NerdTree{{{
Plugin 'xuyuanp/nerdtree-git-plugin'
" }}}

" vim-grepper - A plugin for easily searching through a project {{{
Plugin 'mhinz/vim-grepper'
" }}}

" vim-git - Syntax files for git files {{{
Plugin 'tpope/vim-git'
" }}}

" ctrlp-py-matcher - A faster matcher than ctrlp's build in version {{{
Plugin 'FelikZ/ctrlp-py-matcher'
" }}}

" vim-devicons - Glyphs for VIM {{{
Plugin 'ryanoasis/vim-devicons'
" }}}

" Gita  - Another Git Workflow {{{
Plugin 'lambdalisue/vim-gita'
" }}}
" }}}

" bindings  {{{
let mapleader=';'
nmap <C-e> :NERDTree<CR>
nmap <Leader>e :NERDTreeFind<CR>
nmap <Leader>u :UndotreeToggle<CR>
nmap gm :LivedownToggle<CR>
nmap <Leader>bb :b#<CR>
nmap <Leader>b3 :b#<CR>

" Use gs to search for the selection/motion with Grepper
nmap gs <plug>(GrepperOperator)
vmap gs <plug>(GrepperOperator)
" }}}

" prefs {{{
set hidden

" For some reason, on the version of vim I have on my server, json files are
" taken as Javascript.
autocmd BufNewFile,BufRead *.json set ft=json

" Finally caving and expanding tabs, for everything but makefiles
autocmd FileType make set noexpandtab
autocmd FileType make set tabstop=8
autocmd FileType make set shiftwidth=8
autocmd FileType make set softtabstop=8

" Hide node_modules directories in NERDTree.  Show them with 'f'.
let NERDTreeIgnore=['^node_modules$[[dir]]']
let NERDTreeShowHidden=1

" Show the help for BufExplorer by default.  The bindings are kinda arbitrary.
let g:bufExplorerDefaultHelp=1

" I think one of the whole points of BufExplorer is to make it easy to delete
" NoName buffers.
let g:bufExplorerShowNoName=1

" Ignore editorconfig settings for special views
let g:EditorConfig_exclude_patterns = ['fugitive://.*']
let g:EditorConfig_exclude_patterns = ['scp://.*']
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']

set directory-=.
let &directory=substitute(&directory,',','//,','')

" Try and speed up ctrlp by using ag
if executable("ag")
    let g:ctrlp_user_command = 'ag %s -U -i --nocolor --nogroup --hidden --ignore .git --ignore .svn --ignore .hg --ignore .DS_Store --ignore "**/*.pyc" -g ""'
endif

let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
" }}}

" asthetics {{{

set termguicolors

" colorscheme jaime
colorscheme dracula
" let g:airline_theme='molokai'
let g:airline_theme='bubblegum'

" colorscheme flattened_dark
syntax on

" In gvim, use a font the includes the special powerline symbols.
set guifont=Meslo\ LG\ S\ Regular\ for\ Powerline\ Nerd\ Font\ Complete\ Mono:h11,MesloLGS_NF:h9:cANSI,Meslo_LG_S_for_Powerline:h9:cANSI,Menlo\ for\ Powerline:h11,Meslo\ LG\ S\ Regular\ for\ Powerline:h11

" Show normal mode commands
set showcmd

" Highlight all matches after a search
set hls

" Hide the toolbar in the GUI
set guioptions-=T

" Highlight the current line
set cursorline

" Use bold instead of underline to highlight
hi Search term=bold cterm=bold ctermbg=LightYellow ctermfg=Black guibg=#ffff00 guifg=black

" Use a vertical bar for vertical splits
"
" This looks better, but a space isn't recognized as a line by iTerm.  So the
" natural selection feature doesn't work.
"
" set fillchars+=vert:\ 
" 
" }}}

" indentation {{{

" 4 space tabstops, but still display tab characters with an 8
" character tabstop.
"
set tabstop=8
set softtabstop=4
set shiftwidth=4
set expandtab
" }}}

" file specific settings {{{
augroup file_specific_settings
    autocmd!
    autocmd BufEnter .jshintrc setlocal filetype=json
    autocmd BufEnter .eslintrc setlocal filetype=json
augroup END
" }}}

" windows-specific-settings {{{
if has('win32')
    let $PATH = 'C:\Program Files (x86)\Git\bin;' . $PATH
    set shell=C:\Progra~1\Git\bin\bash.exe
endif
" }}}

" - chris
